services:
  uangpintar:
    build:
      context: .
      dockerfile: Dockerfile
    image: ikhsan816/uangpintar:1.0.0
    container_name: uangpintar
    command: npm start
    ports:
      - "4120:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      DATABASE_URL: ${DATABASE_URL}
      RESEND: ${RESEND}
      REDIS_URL: ${REDIS_URL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      OPENROUTER: ${OPENROUTER}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
    networks:
      - global

networks:
  global:
    external:
      name: uangpintar-network
